function CardDraw (color: number, x: number, y: number, text: string, myImage: Image) {
    fancyText.draw(text, myImage, x, y, 45, color, fancyText.tiny_4)
}
function DeathAndLevel () {
	
}
function CardImage (text: string) {
    Text = img`
        .............................................
        .............................................
        .............................................
        .............................................
        .............................................
        .............................................
        .............................................
        .............................................
        .............................................
        .............................................
        .............................................
        .............................................
        .............................................
        .............................................
        .............................................
        .............................................
        .............................................
        .............................................
        .............................................
        .............................................
        .............................................
        .............................................
        .............................................
        .............................................
        .............................................
        .............................................
        .............................................
        .............................................
        .............................................
        .............................................
        .............................................
        .............................................
        .............................................
        .............................................
        .............................................
        .............................................
        .............................................
        .............................................
        .............................................
        .............................................
        .............................................
        .............................................
        .............................................
        .............................................
        .............................................
        .............................................
        .............................................
        .............................................
        .............................................
        .............................................
        .............................................
        .............................................
        .............................................
        .............................................
        .............................................
        .............................................
        .............................................
        .............................................
        .............................................
        .............................................
        .............................................
        .............................................
        .............................................
        .............................................
        .............................................
        .............................................
        .............................................
        .............................................
        .............................................
        .............................................
        `
    Card = img`
        cccccccccccccccccccccccccccccccccccccccccccccccccc
        c888888888888888888888888888888888888888888888888c
        c888888888888888888888888888888888888888888888888c
        c888888888888888888888888888888888888888888888888c
        c888cccccccccccccccccccccccccccccccccccccccccc888c
        c888cddddddddddddddddddddddddddddddddddddddddc888c
        c888cddddddddddddddddddddddddddddddddddddddddc888c
        c888cddddddddddddddddddddddddddddddddddddddddc888c
        c888cddddddddddddddddddddddddddddddddddddddddc888c
        c888cddddddddddddddddddddddddddddddddddddddddc888c
        c888cddddddddddddddddddddddddddddddddddddddddc888c
        c888cddddddddddddddddddddddddddddddddddddddddc888c
        c888cddddddddddddddddddddddddddddddddddddddddc888c
        c888cddddddddddddddddddddddddddddddddddddddddc888c
        c888cdddd22222222222222222222222222222222ddddc888c
        c888cdddd22222222222222222222222222222222ddddc888c
        c888cdddd2eeeeeeeeeeeeeeeeeeeeeeeeeeeeee2ddddc888c
        c888cdddd2e............................e2ddddc888c
        c888cdddd2e............................e2ddddc888c
        c888cdddd2e............................e2ddddc888c
        c888cdddd2e............................e2ddddc888c
        c888cdddd2e............................e2ddddc888c
        c888cdddd2e............................e2ddddc888c
        c888cdddd2e............................e2ddddc888c
        c888cdddd2e............................e2ddddc888c
        c888cdddd2e............................e2ddddc888c
        c888cdddd2e............................e2ddddc888c
        c888cdddd2e............................e2ddddc888c
        c888cdddd2e............................e2ddddc888c
        c888cdddd2e............................e2ddddc888c
        c888cdddd2e............................e2ddddc888c
        c888cdddd2e............................e2ddddc888c
        c888cdddd2e............................e2ddddc888c
        c888cdddd2e............................e2ddddc888c
        c888cdddd2e............................e2ddddc888c
        c888cdddd2e............................e2ddddc888c
        c888cdddd2e............................e2ddddc888c
        c888cdddd2e............................e2ddddc888c
        c888cdddd2e............................e2ddddc888c
        c888cdddd2e............................e2ddddc888c
        c888cdddd2e............................e2ddddc888c
        c888cdddd2e............................e2ddddc888c
        c888cdddd2e............................e2ddddc888c
        c888cdddd2e............................e2ddddc888c
        c888cdddd2e2222222222222222222222222222e2ddddc888c
        c888cdddd2eeeeeeeeeeeeeeeeeeeeeeeeeeeeee2ddddc888c
        c888cddddddddddddddddddddddddddddddddddddddddc888c
        c888cddddddddddddddddddddddddddddddddddddddddc888c
        c888cddddddddddddddddddddddddddddddddddddddddc888c
        c888cddddddddddddddddddddddddddddddddddddddddc888c
        c888cddddddddddddddddddddddddddddddddddddddddc888c
        c888cddddddddddddddddddddddddddddddddddddddddc888c
        c888cddddddddddddddddddddddddddddddddddddddddc888c
        c888cddddddddddddddddddddddddddddddddddddddddc888c
        c888cddddddddddddddddddddddddddddddddddddddddc888c
        c888cddddddddddddddddddddddddddddddddddddddddc888c
        c888cddddddddddddddddddddddddddddddddddddddddc888c
        c888cddddddddddddddddddddddddddddddddddddddddc888c
        c888cddddddddddddddddddddddddddddddddddddddddc888c
        c888cddddddddddddddddddddddddddddddddddddddddc888c
        c888cddddddddddddddddddddddddddddddddddddddddc888c
        c888cddddddddddddddddddddddddddddddddddddddddc888c
        c888cddddddddddddddddddddddddddddddddddddddddc888c
        c888cddddddddddddddddddddddddddddddddddddddddc888c
        c888cddddddddddddddddddddddddddddddddddddddddc888c
        c888cddddddddddddddddddddddddddddddddddddddddc888c
        c888cddddddddddddddddddddddddddddddddddddddddc888c
        c888cddddddddddddddddddddddddddddddddddddddddc888c
        c888cddddddddddddddddddddddddddddddddddddddddc888c
        c888cddddddddddddddddddddddddddddddddddddddddc888c
        c888cddddddddddddddddddddddddddddddddddddddddc888c
        c888cddddddddddddddddddddddddddddddddddddddddc888c
        c888cddddddddddddddddddddddddddddddddddddddddc888c
        c888cddddddddddddddddddddddddddddddddddddddddc888c
        c888cddddddddddddddddddddddddddddddddddddddddc888c
        c888cccccccccccccccccccccccccccccccccccccccccc888c
        c888888888888888888888888888888888888888888888888c
        c888888888888888888888888888888888888888888888888c
        c888888888888888888888888888888888888888888888888c
        cccccccccccccccccccccccccccccccccccccccccccccccccc
        `
    if (text == "Cut") {
        OutputCardImg = assets.image`myImage6`
        EnergyImgOutput = assets.image`EC1`
        EnemiesImg = "6 DMG"
        Card.drawTransparentImage(assets.image`EC1`, 23, 0)
    } else if (text == "abc") {
    	
    } else {
    	
    }
    CardDraw(7, 7, 48, "6DMG", Card)
    CardDraw(10, 5, 6, text, Card)
    return Card
}
let EnemiesImg = ""
let EnergyImgOutput: Image = null
let OutputCardImg: Image = null
let Card: Image = null
let Text: Image = null
let mySprite = sprites.create(CardImage("Cut"), SpriteKind.Player)
let Floor = 10
let ElitesFought = 2
