function CardText (color: number, x: number, y: number, text: string, myImage: Image) {
    fancyText.draw(text, myImage, x, y, 45, color, fancyText.tiny_4)
}
function CardImage (text: string) {
    Text = img`
        .............................................
        .............................................
        .............................................
        .............................................
        .............................................
        .............................................
        .............................................
        .............................................
        .............................................
        .............................................
        .............................................
        .............................................
        .............................................
        .............................................
        .............................................
        .............................................
        .............................................
        .............................................
        .............................................
        .............................................
        .............................................
        .............................................
        .............................................
        .............................................
        .............................................
        .............................................
        .............................................
        .............................................
        .............................................
        .............................................
        .............................................
        .............................................
        .............................................
        .............................................
        .............................................
        .............................................
        .............................................
        .............................................
        .............................................
        .............................................
        .............................................
        .............................................
        .............................................
        .............................................
        .............................................
        .............................................
        .............................................
        .............................................
        .............................................
        .............................................
        .............................................
        .............................................
        .............................................
        .............................................
        .............................................
        .............................................
        .............................................
        .............................................
        .............................................
        .............................................
        .............................................
        .............................................
        .............................................
        .............................................
        .............................................
        .............................................
        .............................................
        .............................................
        .............................................
        .............................................
        `
    Card = img`
        cccccccccccccccccccccccccccccccccccccccccccccccccc
        c888888888888888888888888888888888888888888888888c
        c888888888888888888888888888888888888888888888888c
        c888888888888888888888888888888888888888888888888c
        c888cccccccccccccccccccccccccccccccccccccccccc888c
        c888cddddddddddddddddddddddddddddddddddddddddc888c
        c888cddddddddddddddddddddddddddddddddddddddddc888c
        c888cddddddddddddddddddddddddddddddddddddddddc888c
        c888cddddddddddddddddddddddddddddddddddddddddc888c
        c888cddddddddddddddddddddddddddddddddddddddddc888c
        c888cddddddddddddddddddddddddddddddddddddddddc888c
        c888cddddddddddddddddddddddddddddddddddddddddc888c
        c888cddddddddddddddddddddddddddddddddddddddddc888c
        c888cddddddddddddddddddddddddddddddddddddddddc888c
        c888cdddd22222222222222222222222222222222ddddc888c
        c888cdddd22222222222222222222222222222222ddddc888c
        c888cdddd2eeeeeeeeeeeeeeeeeeeeeeeeeeeeee2ddddc888c
        c888cdddd2e............................e2ddddc888c
        c888cdddd2e............................e2ddddc888c
        c888cdddd2e............................e2ddddc888c
        c888cdddd2e............................e2ddddc888c
        c888cdddd2e............................e2ddddc888c
        c888cdddd2e............................e2ddddc888c
        c888cdddd2e............................e2ddddc888c
        c888cdddd2e............................e2ddddc888c
        c888cdddd2e............................e2ddddc888c
        c888cdddd2e............................e2ddddc888c
        c888cdddd2e............................e2ddddc888c
        c888cdddd2e............................e2ddddc888c
        c888cdddd2e............................e2ddddc888c
        c888cdddd2e............................e2ddddc888c
        c888cdddd2e............................e2ddddc888c
        c888cdddd2e............................e2ddddc888c
        c888cdddd2e............................e2ddddc888c
        c888cdddd2e............................e2ddddc888c
        c888cdddd2e............................e2ddddc888c
        c888cdddd2e............................e2ddddc888c
        c888cdddd2e............................e2ddddc888c
        c888cdddd2e............................e2ddddc888c
        c888cdddd2e............................e2ddddc888c
        c888cdddd2e............................e2ddddc888c
        c888cdddd2e............................e2ddddc888c
        c888cdddd2e............................e2ddddc888c
        c888cdddd2e............................e2ddddc888c
        c888cdddd2e2222222222222222222222222222e2ddddc888c
        c888cdddd2eeeeeeeeeeeeeeeeeeeeeeeeeeeeee2ddddc888c
        c888cddddddddddddddddddddddddddddddddddddddddc888c
        c888cddddddddddddddddddddddddddddddddddddddddc888c
        c888cddddddddddddddddddddddddddddddddddddddddc888c
        c888cddddddddddddddddddddddddddddddddddddddddc888c
        c888cddddddddddddddddddddddddddddddddddddddddc888c
        c888cddddddddddddddddddddddddddddddddddddddddc888c
        c888cddddddddddddddddddddddddddddddddddddddddc888c
        c888cddddddddddddddddddddddddddddddddddddddddc888c
        c888cddddddddddddddddddddddddddddddddddddddddc888c
        c888cddddddddddddddddddddddddddddddddddddddddc888c
        c888cddddddddddddddddddddddddddddddddddddddddc888c
        c888cddddddddddddddddddddddddddddddddddddddddc888c
        c888cddddddddddddddddddddddddddddddddddddddddc888c
        c888cddddddddddddddddddddddddddddddddddddddddc888c
        c888cddddddddddddddddddddddddddddddddddddddddc888c
        c888cddddddddddddddddddddddddddddddddddddddddc888c
        c888cddddddddddddddddddddddddddddddddddddddddc888c
        c888cddddddddddddddddddddddddddddddddddddddddc888c
        c888cddddddddddddddddddddddddddddddddddddddddc888c
        c888cddddddddddddddddddddddddddddddddddddddddc888c
        c888cddddddddddddddddddddddddddddddddddddddddc888c
        c888cddddddddddddddddddddddddddddddddddddddddc888c
        c888cddddddddddddddddddddddddddddddddddddddddc888c
        c888cddddddddddddddddddddddddddddddddddddddddc888c
        c888cddddddddddddddddddddddddddddddddddddddddc888c
        c888cddddddddddddddddddddddddddddddddddddddddc888c
        c888cddddddddddddddddddddddddddddddddddddddddc888c
        c888cddddddddddddddddddddddddddddddddddddddddc888c
        c888cddddddddddddddddddddddddddddddddddddddddc888c
        c888cccccccccccccccccccccccccccccccccccccccccc888c
        c888888888888888888888888888888888888888888888888c
        c888888888888888888888888888888888888888888888888c
        c888888888888888888888888888888888888888888888888c
        cccccccccccccccccccccccccccccccccccccccccccccccccc
        `
    if (text == "Cut") {
    	
    } else if (text == "abc") {
    	
    } else {
    	
    }
    CardText(7, 7, 48, "6DMG", Card)
    CardText(10, 5, 6, text, Card)
    return Card
}
let Card: Image = null
let Text: Image = null
let mySprite = sprites.create(CardImage("Cut"), SpriteKind.Player)
let CardImgArray = [assets.image`myImage6`]
let CardNamesArray = [
"Cut",
"Block",
"Inferno",
"Wildfire"
]
// Array #1 is for Defending
// Array #2 is for the DMG the card does
let AllCardDFNDDMGArray = [[
0,
5,
3,
0
], [
6,
0,
0,
14
]]
// Value can be
// 1. Empty
// 2. Fire
// 3. Water
// 4. Electric
// 5. Air
// 6. Random (switches each turn to 2-5)
let AllCardCreateConsumeElementArray = [[
"None",
"None",
"Fire",
"None"
], [
"None",
"None",
"None",
"Fire"
]]
